// File generated by hand, not by the FlutterFire CLI — this sandbox has no
// Firebase login, so it can't run `flutterfire configure` to register real
// iOS/Android apps under the wills-severe-weather-alerts project.
//
// The values below that come from the *existing* web app config
// (apiKey, projectId, storageBucket, messagingSenderId) are real and shared
// across every platform in the same Firebase project — safe to commit, same
// as they already are in the web app's src/firebase.ts.
//
// The `appId` fields are NOT real — Firebase mints a distinct App ID per
// platform app you register. To finish this:
//   1. Firebase console → Project settings → Add app → Android, using
//      applicationId "com.willsweatheralerts.wills_weather_alerts"
//      (see mobile/android/app/build.gradle). Download google-services.json
//      into mobile/android/app/.
//   2. Add app → iOS, using bundle ID "com.willsweatheralerts.willsWeatherAlerts"
//      (see mobile/ios/Runner.xcodeproj). Download GoogleService-Info.plist
//      into mobile/ios/Runner/.
//   3. Replace ANDROID_APP_ID_PLACEHOLDER / IOS_APP_ID_PLACEHOLDER below with
//      the appId values Firebase shows you in step 1/2 (format
//      "1:905467059263:android:..." / "...:ios:...").
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8o6BNR8V5DIdgml-P5EB7-lpICqGek8',
    appId: '1:905467059263:web:587de4c318059bb819ac8a',
    messagingSenderId: '905467059263',
    projectId: 'wills-severe-weather-alerts',
    authDomain: 'wills-severe-weather-alerts.firebaseapp.com',
    storageBucket: 'wills-severe-weather-alerts.firebasestorage.app',
  );

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyAQ8o6BNR8V5DIdgml-P5EB7-lpICqGek8',
    appId: 'ANDROID_APP_ID_PLACEHOLDER',
    messagingSenderId: '905467059263',
    projectId: 'wills-severe-weather-alerts',
    storageBucket: 'wills-severe-weather-alerts.firebasestorage.app',
  );

  static const ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ8o6BNR8V5DIdgml-P5EB7-lpICqGek8',
    appId: 'IOS_APP_ID_PLACEHOLDER',
    messagingSenderId: '905467059263',
    projectId: 'wills-severe-weather-alerts',
    storageBucket: 'wills-severe-weather-alerts.firebasestorage.app',
    iosBundleId: 'com.willsweatheralerts.willsWeatherAlerts',
  );
}
